=== fema-ffrd/specs/reference/base/schemas/action.json
{
  "$id": "./action.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Action",
  "description": "A generic action (e.g. model simulatuion, data or transformation step) with typed inputs/outputs, parameterized paths, and optional operator parameters. See specific action schemas for specialized actions, attrubutes, and parameters.",
  "$defs": {
    "Action": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "attributes"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Logical name for this action (e.g., step name in a workflow)."
        },
        "type": {
          "type": "string",
          "description": "Action type identifier (tool/operator name). In future versions may be an enum supporting named types such as `link`, `utils`, `extract`, and `run`"
        },
        "description": {
          "type": "string",
          "description": "Human-readable summary of the action."
        },
        "attributes": {
          "type": "object",
          "description": "Primitive attributes used for template substitution in path strings.",
          "additionalProperties": {
            "type": [
              "string",
              "number",
              "boolean",
              "array"
            ]
          }
        },
        "inputs": {
          "type": "array",
          "items": {
            "$ref": "./data.json#/$defs/DataSource"
          },
          "description": "One or more inputs."
        },
        "outputs": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "./data.json#/$defs/DataSource"
          },
          "description": "One or more outputs."
        },
        "stores": {
          "type": "array",
          "items": {
            "$ref": "./store.json#/$defs/Store"
          },
          "description": "List of storage configurations for this action."
        }
      }
    }
  },
  "$ref": "#/$defs/Action"
}

=== fema-ffrd/specs/reference/ras/v660/examples/ras-unsteady-payload-S3-2.json
{
  "name": "run-unsteady-lavon-plan01",
  "type": "ras.run_unsteady_simulation",
  "attributes": {
    "geom": "01",
    "plan": "01",
    "modelPrefix": "lavon",
    "base-hydraulics-directory": "hydraulics",
    "outputdir": "outputs"
  },
  "inputs": [
    {
      "name": "ras_model_files",
      "paths": {
        "b_file": "stac/ras/{ATTR:modelPrefix}.b{ATTR:geom}",
        "o_file": "stac/ras/{ATTR:modelPrefix}.ic.o{ATTR:plan}",
        "tmp_hdf": "stac/ras/{ATTR:modelPrefix}.p{ATTR:plan}.tmp.hdf",
        "x_file": "stac/ras/{ATTR:modelPrefix}.x{ATTR:plan}"
      },
      "store_name": "stac-demo"
    }
  ],
  "outputs": [
    {
      "name": "hdf_output",
      "paths": {
        "hdf_output": "stac/ras/{ATTR:modelPrefix}/{ATTR:outputdir}/{ATTR:modelPrefix}.p{ATTR:plan}.hdf"
      },
      "store_name": "local-mount"
    }
  ],
  "stores": [
    {
      "name": "stac-demo",
      "store_type": "S3",
      "params": {
        "root": "trinity-pilot"
      }
    },
    {
      "name": "local-mount",
      "store_type": "FS",
      "params": {
        "root": "/data"
      }
    }
  ]
}

=== fema-ffrd/specs/reference/hms/hms-golang/examples/hms-simulation-payload-FS.json
{
  "name": "hms-simulation-payload-FS2",
  "type": "action.hms.run_simulation",
  "attributes": {
    "storms_catalog": "/conformance/storm-catalog/storms/",
    "model-name": "trinity",
    "outputdir": "outputs",
    "base-hydrology-directory": "hydrology",
    "simulation": "apr-may-1990",
    "met-name": "apr_may_1990",
    "control-name": "apr_may_1990",
    "basin-name": "trinity_apr_may_1990",
    "exported-precip-name": "exported-precip_trinity.p01.tmp.hdf",
    "storm-name": "test",
    "scenario": "calibration",
    "outputroot": "outputs",
    "CC_EVENT_IDENTIFIER": "10",
    "exported-peak-paths": [
      "//amon-g-carter_s030/FLOW//1Hour/RUN:SST/",
      "//wilson-ck_s010/PRECIP-INC//1Hour/RUN:SST/"
    ],
    "exported-peak-durations": [
      1,
      24,
      48,
      72
    ],
    "peak-datasource-name": "peaks",
    "log-datasource-name": "logs"
  },
  "inputs": [
    {
      "name": "hms",
      "paths": {
        "control-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::control-name}.control",
        "met-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::met-name}.met",
        "simulation-dss": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.dss",
        "grid-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.grid",
        "paired-data-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.pdata",
        "hms-project-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.hms",
        "run-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.run",
        "sqlite-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::basin-name}.sqlite",
        "terrain-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.terrain",
        "basin-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::basin-name}.basin"
      },
      "store_name": "local-mount"
    },
    {
      "name": "hms-data",
      "paths": {
        "paired-data-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/trinity.pdata",
        "normalization-file": ""
      },
      "store_name": "local-mount"
    },
    {
      "name": "storms",
      "paths": {
        "default": "{ATTR::scenario}/{ATTR::outputroot}/storm-catalog/storms.csv"
      },
      "store_name": "local-mount"
    },
    {
      "name": "storm-catalog",
      "paths": {
        "default": "{ATTR::scenario}/storm-catalog/storms/{ATTR::CC_EVENT_IDENTIFIER}.dss"
      },
      "store_name": "local-mount"
    },
    {
      "name": "basinfiles",
      "paths": {
        "basin-prefix": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}"
      },
      "store_name": "local-mount"
    },
    {
      "name": "controlfiles",
      "paths": {
        "control-prefix": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/data/controlspecs"
      },
      "store_name": "local-mount"
    }
  ],
  "outputs": [
    {
      "name": "simulation-dss",
      "paths": {
        "default": "{ATTR::scenario}/{ATTR::outputroot}/event-data/{ATTR::CC_EVENT_IDENTIFIER}/{ATTR::base-hydrology-directory}/{ATTR::simulation}.dss"
      },
      "store_name": "local-mount"
    },
    {
      "name": "excess-precip",
      "paths": {
        "default": "{ATTR::scenario}/{ATTR::outputroot}/event-data/{ATTR::CC_EVENT_IDENTIFIER}/{ATTR::base-hydrology-directory}/{ATTR::exported-precip-name}"
      },
      "store_name": "local-mount"
    },
    {
      "name": "peaks",
      "paths": {
        "1": "{ATTR::scenario}/{ATTR::outputroot}/summary-data/{ATTR::base-hydrology-directory}/1h_peaks_{ATTR::CC_EVENT_IDENTIFIER}.csv",
        "24": "{ATTR::scenario}/{ATTR::outputroot}/summary-data/{ATTR::base-hydrology-directory}/24h_peaks_{ATTR::CC_EVENT_IDENTIFIER}.csv",
        "48": "{ATTR::scenario}/{ATTR::outputroot}/summary-data/{ATTR::base-hydrology-directory}/48h_peaks_{ATTR::CC_EVENT_IDENTIFIER}.csv",
        "72": "{ATTR::scenario}/{ATTR::outputroot}/summary-data/{ATTR::base-hydrology-directory}/72h_peaks_{ATTR::CC_EVENT_IDENTIFIER}.csv"
      },
      "store_name": "local-mount"
    },
    {
      "name": "logs",
      "paths": {
        "failed_events": "{ATTR::scenario}/{ATTR::outputroot}/logs/{ATTR::base-hydrology-directory}/failed_events_{ATTR::CC_EVENT_IDENTIFIER}.csv",
        "time_log": "{ATTR::scenario}/{ATTR::outputroot}/logs/{ATTR::base-hydrology-directory}/timings_{ATTR::CC_EVENT_IDENTIFIER}.csv"
      },
      "store_name": "local-mount"
    }
  ],
  "stores": [
    {
      "name": "local-mount",
      "store_type": "FS",
      "params": {
        "root": "ffrd-trinity"
      }
    }
  ]
}

=== fema-ffrd/specs/reference/ras/v660/examples/ras-unsteady-payload-FS.json
{
  "name": "run-unsteady-lavon-plan01",
  "type": "ras.run_unsteady_simulation",
  "attributes": {
    "geom": "01",
    "plan": "01",
    "modelPrefix": "lavon",
    "base-hydraulics-directory": "data",
    "outputdir": "outputs"
  },
  "inputs": [
    {
      "name": "ras_model_files",
      "paths": {
        "b_file": "{ATTR::modelPrefix}.b{ATTR::geom}",
        "o_file": "{ATTR::modelPrefix}.ic.o{ATTR::plan}",
        "tmp_hdf": "{ATTR::modelPrefix}.p{ATTR::plan}.tmp.hdf",
        "x_file": "{ATTR::modelPrefix}.x{ATTR::plan}"
      },
      "store_name": "local-mount"
    }
  ],
  "outputs": [
    {
      "name": "hdf_output",
      "paths": {
        "hdf_output": "{ATTR::modelPrefix}.p{ATTR::plan}.hdf"
      },
      "store_name": "local-mount"
    }
  ],
  "stores": [
    {
      "name": "local-mount",
      "store_type": "FS",
      "params": {
        "root": "trinity-pilot"
      }
    }
  ]
}

=== fema-ffrd/specs/reference/hms/v412/examples/hms-simulation-payload-FS copy.json
{
  "name": "hms-simulation-payload-FS",
  "type": "action.hms.run_simulation",
  "attributes": {
    "storms_catalog": "/conformance/storm-catalog/storms/",
    "model-name": "trinity",
    "outputdir": "outputs",
    "base-hydrology-directory": "hydrology",
    "simulation": "SST",
    "met-name": "SST",
    "control-name": "SST",
    "basin-name": "trinity_sst",
    "exported-precip-name": "exported-precip_trinity.p01.tmp.hdf",
    "storm-name": "test",
    "scenario": "conformance",
    "outputroot": "outputs",
    "CC_EVENT_IDENTIFIER": "10",
    "exported-peak-paths": [
      "//amon-g-carter_s030/FLOW//1Hour/RUN:SST/",
      "//wilson-ck_s010/PRECIP-INC//1Hour/RUN:SST/"
    ],
    "exported-peak-durations": [
      1,
      24,
      48,
      72
    ],
    "peak-datasource-name": "peaks",
    "log-datasource-name": "logs"
  },
  "inputs": [
    {
      "name": "hms",
      "paths": {
        "control-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::control-name}.control",
        "met-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::met-name}.met",
        "simulation-dss": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.dss",
        "grid-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.grid",
        "paired-data-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.pdata",
        "hms-project-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.hms",
        "run-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.run",
        "sqlite-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::basin-name}.sqlite",
        "terrain-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::model-name}.terrain",
        "basin-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/{ATTR::basin-name}.basin"
      },
      "store_name": "FFRD"
    },
    {
      "name": "hms-data",
      "paths": {
        "paired-data-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/data/paired_data.dss",
        "normalization-file": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/data/trinity_72hr_100yr_in.tif"
      },
      "store_name": "FFRD"
    },
    {
      "name": "storms",
      "paths": {
        "default": "{ATTR::scenario}/{ATTR::outputroot}/storm-catalog/storms.csv"
      },
      "store_name": "FFRD"
    },
    {
      "name": "storm-catalog",
      "paths": {
        "default": "{ATTR::scenario}/storm-catalog/storms/{ATTR::CC_EVENT_IDENTIFIER}.dss"
      },
      "store_name": "FFRD"
    },
    {
      "name": "basinfiles",
      "paths": {
        "basin-prefix": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}"
      },
      "store_name": "FFRD"
    },
    {
      "name": "controlfiles",
      "paths": {
        "control-prefix": "{ATTR::scenario}/{ATTR::base-hydrology-directory}/{ATTR::model-name}/data/controlspecs"
      },
      "store_name": "FFRD"
    }
  ],
  "outputs": [
    {
      "name": "simulation-dss",
      "paths": {
        "default": "{ATTR::scenario}/{ATTR::outputroot}/event-data/{ATTR::CC_EVENT_IDENTIFIER}/{ATTR::base-hydrology-directory}/{ATTR::simulation}.dss"
      },
      "store_name": "FFRD"
    },
    {
      "name": "excess-precip",
      "paths": {
        "default": "{ATTR::scenario}/{ATTR::outputroot}/event-data/{ATTR::CC_EVENT_IDENTIFIER}/{ATTR::base-hydrology-directory}/{ATTR::exported-precip-name}"
      },
      "store_name": "FFRD"
    },
    {
      "name": "peaks",
      "paths": {
        "1": "{ATTR::scenario}/{ATTR::outputroot}/summary-data/{ATTR::base-hydrology-directory}/1h_peaks_{ATTR::CC_EVENT_IDENTIFIER}.csv",
        "24": "{ATTR::scenario}/{ATTR::outputroot}/summary-data/{ATTR::base-hydrology-directory}/24h_peaks_{ATTR::CC_EVENT_IDENTIFIER}.csv",
        "48": "{ATTR::scenario}/{ATTR::outputroot}/summary-data/{ATTR::base-hydrology-directory}/48h_peaks_{ATTR::CC_EVENT_IDENTIFIER}.csv",
        "72": "{ATTR::scenario}/{ATTR::outputroot}/summary-data/{ATTR::base-hydrology-directory}/72h_peaks_{ATTR::CC_EVENT_IDENTIFIER}.csv"
      },
      "store_name": "FFRD"
    },
    {
      "name": "logs",
      "paths": {
        "failed_events": "{ATTR::scenario}/{ATTR::outputroot}/logs/{ATTR::base-hydrology-directory}/failed_events_{ATTR::CC_EVENT_IDENTIFIER}.csv",
        "time_log": "{ATTR::scenario}/{ATTR::outputroot}/logs/{ATTR::base-hydrology-directory}/timings_{ATTR::CC_EVENT_IDENTIFIER}.csv"
      },
      "store_name": "FFRD"
    }
  ],
  "stores": [
    {
      "name": "FFRD",
      "store_type": "S3",
      "params": {
        "root": "model-library/ffrd-trinity"
      }
    }
  ]
}
